# Generated by Django 5.2.1 on 2025-12-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sale_operation_type_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='operation_type',
            field=models.CharField(choices=[('SHOP', 'Shop'), ('SALON', 'Salon'), ('STUDIO', 'Studio')], default='SHOP', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='operation_type',
            field=models.CharField(choices=[('SHOP', 'Shop'), ('SALON', 'Salon'), ('STUDIO', 'Studio'), ('BOTH', 'All')], default='SHOP', max_length=10),
        ),
    ]
