#!/bin/bash

# Guide to configure printer network settings
# Since printer is connected via USB, we'll guide through printer menu

echo "========================================"
echo "🖨️  CONFIGURE PRINTER FOR NETWORK"
echo "========================================"
echo ""
echo "To enable network printing, you need to configure the printer"
echo "using its physical buttons and menu system."
echo ""
echo "Step 1: Access Printer Menu"
echo "  - Use the buttons on your printer"
echo "  - Look for 'Menu', 'Settings', or 'Setup' button"
echo ""
echo "Step 2: Navigate to Network Settings"
echo "  - Go to: Network Settings → TCP/IP"
echo "  - OR: Settings → Network → TCP/IP"
echo "  - OR: Setup → Network → TCP/IP"
echo ""
echo "Step 3: Enable Network/Enable TCP/IP"
echo "  - Find option: 'Enable TCP/IP' or 'Network Enable'"
echo "  - Set it to: ON or ENABLED"
echo ""
echo "Step 4: Configure IP Address (Choose one):"
echo ""
echo "  Option A: DHCP (Automatic - Recommended)"
echo "    - Set 'IP Mode' to 'DHCP' or 'Auto'"
echo "    - Printer will get IP from router automatically"
echo "    - Note the IP address shown"
echo ""
echo "  Option B: Static IP (Manual)"
echo "    - Set 'IP Mode' to 'Static' or 'Manual'"
echo "    - Enter IP: 192.168.1.50 (or any free IP)"
echo "    - Subnet: 255.255.255.0"
echo "    - Gateway: 192.168.1.1"
echo ""
echo "Step 5: Enable ESC/POS Port"
echo "  - Find: 'Port 9100' or 'RAW Port' or 'ESC/POS Port'"
echo "  - Set to: ENABLED or ON"
echo ""
echo "Step 6: Save Settings"
echo "  - Save/Apply the settings"
echo "  - Printer may restart"
echo ""
echo "Step 7: Connect Ethernet Cable"
echo "  - Connect Ethernet cable from printer to router"
echo "  - Wait 30-60 seconds for printer to get IP"
echo ""
echo "Step 8: Find the IP Address"
echo "  - Check printer display/menu for IP address"
echo "  - OR print network config page"
echo "  - OR check router admin (192.168.1.1)"
echo ""
echo "========================================"
echo "After configuration, test with:"
echo "  ./test-print-simple.sh <printer-ip>"
echo "========================================"
echo ""

# Check if printer is available via USB
echo "Checking USB printer availability..."
if curl -s http://localhost:3333/printers | grep -q "USB"; then
    echo "✅ USB printer detected"
    echo ""
    echo "You can test USB printing while setting up network:"
    echo "  ./test-print-usb.sh"
else
    echo "⚠️  USB printer not detected in Print Bridge"
fi

echo ""
echo "Need help? Check printer manual for:"
echo "  - Network configuration"
echo "  - TCP/IP settings"
echo "  - ESC/POS port configuration"

